import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run clean-api-docs order && npm run gen-api-docs order
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories, mirroring the pattern shared across the
 * warehouse-systems documentation sites: Overview, Business Context,
 * Domain-Driven Design, API Reference, Ecosystem, AI Ecosystem (MCP),
 * Analytics, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/domain-vision'},
      items: ['business-context/ubiquitous-language'],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/subdomain-classification'},
      items: [
        'ddd/aggregates-and-invariants',
        'ddd/domain-events',
        'ddd/use-cases',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/context-map'},
      items: [],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics',
      collapsed: false,
      items: ['analytics/order-funnel-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-http-consumer-of-inventory-and-wes-not-shared-code',
        'adr/0003-ship-complete-default-and-fail-closed-allocation',
        'adr/0004-cancellation-boundary-at-release',
        'adr/0005-choreographed-release-via-kafka',
        'adr/0006-analytical-data-product',
        'adr/0007-adopt-fleet-micro-frontend-console',
        'adr/0008-fulfillment-class-demand-shape-classifier',
        'adr/0009-standard-metrics-convention',
        'adr/0010-mcp-inbound-adapter',
        'adr/0011-adopt-fleet-rest-identity',
        'adr/0012-remove-rest-mcp-bearer-auth',
        'adr/0013-process-path-selection-as-a-domain-policy',
        'adr/0014-promise-derived-from-fulfillment-capability',
        'adr/0015-wes-work-planning-path-capacity-changed-wired',
        'adr/0016-eligibility-driven-process-path-selection',
        'adr/0017-per-shipment-group-promising',
        'adr/0018-repromise-order-consumer-and-order-repromised',
        'adr/0019-promise-kpis-on-order-funnel',
        'adr/0020-network-originated-demand-hold-and-deadline-feasibility',
        'adr/0021-multi-path-attribute-driven-routing',
      ],
    },
  ],
};

export default sidebars;
