import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories, mirroring the pattern shared across the
 * warehouse-systems documentation sites: Overview, Business Context,
 * Domain-Driven Design, API Reference, Ecosystem, Analytics, Architecture
 * Decision Records. This service has no "AI Ecosystem (MCP)" category yet —
 * no MCP adapter exists in v1 (see CLAUDE.md's deferred scope).
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/domain-vision'},
      items: ['business-context/ubiquitous-language'],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/subdomain-classification'},
      items: [
        'ddd/aggregates-and-invariants',
        'ddd/domain-events',
        'ddd/use-cases',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/context-map'},
      items: [],
    },
    {
      type: 'category',
      label: 'Analytics',
      collapsed: false,
      items: ['analytics/order-funnel-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-http-consumer-of-inventory-and-wes-not-shared-code',
        'adr/0003-ship-complete-default-and-fail-closed-allocation',
        'adr/0004-cancellation-boundary-at-release',
        'adr/0005-choreographed-release-via-kafka',
        'adr/0006-analytical-data-product',
        'adr/0007-adopt-fleet-micro-frontend-console',
      ],
    },
  ],
};

export default sidebars;
